### ISSUE TITLE
Can you also remove other console methods?

### ISSUE THREAD

**Issue by Evertt** [xiaoxian521/vite-plugin-remove-console#6] opened 2022-08-22 10:17 UTC
Like `console.debug()`, `console.info()`.
And I'm thinking of `console.time()` and all its related methods, and `console.profile()` and all its related methods, and `console.trace()`.

All of those methods seem helpful to me in development, but I'd probably want to remove in production. Maybe even `console.warn()` although I think I'd probably want to keep `console.error()` in production.

Let me know what you think.

**Comment by xiaoxian521** [comment] 2022-08-22 10:28
Duplicate of #4

**Comment by xiaoxian521** [comment] 2022-08-22 10:31
All are supported, but I don't plan to support it here. You can refer to [utils](https://github.com/xiaoxian521/vite-plugin-remove-console/blob/main/src/utils.ts#L12) here to expand

**Comment by Evertt** [comment] 2022-08-22 10:32
It has some overlap with #4, but it's not a complete duplicate. First of all, I'm not asking for you to give us options. I'm just asking if you're willing to include more console methods in the default behavior of this plugin.

And yes I've already forked this repo and I'm editing `utils` as we speak.

**Comment by xiaoxian521** [comment] 2022-08-22 10:34
Regarding the syntax of [transform](https://github.com/xiaoxian521/vite-plugin-remove-console/blob/main/src/transform.js), you can refer to [gogocode](https://github.com/thx/ gogocode)

**Closed** 2022-08-22 10:40 UTC

**Comment by xiaoxian521** [comment] 2023-02-14 05:14
Currently supported, please upgrade to the latest version
